In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [5]:
np.random.randn(2).reshape(-1,1)

array([[-1.07296862],
       [ 0.86540763]])

In [9]:
np.random.rand(1)

array([0.20445225])

In [12]:
np.random.randn(2, 2)

array([[ 0.18121427,  0.56434487],
       [-0.56651023,  0.7299756 ]])

In [14]:
mask = (1 < 0)

In [15]:
mask

False